const assert=require('assert/strict'),path=require('path'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH});try{const page=await b.newPage({timezoneId:'America/La_Paz'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/^https?:/,r=>r.abort());await page.goto(pathToFileURL(path.resolve(process.env.PANEL_TEST||'pedidos.html')).href);
const checks=await page.evaluate(()=>{let checks=[];const check=(n,v)=>checks.push([n,!!v]);const k=stockClave({codigo:'CH1129'});function pedido(id,u,f,chk){return {id,cliente:id,fecha:f,productos:[{codigo:'CH1129',desc:'TITANIO LATEX',medida:'140x190',cant:u,chk:chk||''}]};}function seed(cantidades,dep=0){STOCK=stockVacio();STOCK.c={f:todayStr(),u:{[k]:dep}};STATE=cantidades.map((u,i)=>pedido('pasado'+i,u,diasAtras(1+i*4)));STOCK_MEMO={};}function o(){return stockData().lista.find(x=>x.k===k);}
// 09/09 (§4dg): con la regla que confirmó el dueño, «unico» es solo para lo vendido por Eduardo; 1–2 unidades del equipo son «lenta». Reposición igual: ninguna.
seed([1,1]);let x=o();check('2 unidades en 2 pedidos no generan reposición',x.pedir===0&&x.aviso==='lenta'&&x.corte===null);check('se clasifica como poca rotación',x.rotacion==='baja');abrirStock();check('el panel explica que solo cubre pedidos confirmados',document.getElementById('stock-body').textContent.includes('Poca rotación: solo pedidos confirmados'));
STATE.push(pedido('pendiente',2,diasAdelante(1)));x=o();check('baja rotación cubre 2 pendientes sin reserva extra',x.pedir===2);STOCK.c.u[k]=1;check('resta la unidad disponible',o().pedir===1);STOCK.c.u[k]=2;check('si alcanza no repone',o().pedir===0);
// 09/09 (§4dg): el dueño eligió que una venta grande del equipo SÍ cuente como rotación (media: una sola entrega no es «sostenida»).
seed([40]);check('venta grande única del equipo sí cuenta como rotación (decisión del dueño 09/09)',o().rotacion==='media'&&o().pedir>0);
seed([3,3,3,3]);x=o();check('12 unidades usan reserva media',x.rotacion==='media'&&x.cubrir===3&&x.margen===2);check('media calcula plazo y reserva reducida',x.pedir===Math.ceil(x.porDia*(x.lead+2+3)-1e-9));
seed([14,14,14,14]);x=o();check('alta sostenida mantiene 7 días de cobertura',x.rotacion==='alta'&&x.cubrir===7);check('alta repone más que media',x.pedir>4);
seed([1,1]);STATE.push(pedido('Almohadas',2,diasAdelante(2),'ok'));x=o();check('marca hay exige revisión y muestra reposición provisional',x.revisarStock&&x.aviso==='revisar'&&x.pedir===2);abrirStockPedidos(k);check('el detalle explica la discrepancia',document.getElementById('modal-box').textContent.includes('diferencia entre marcas e inventario'));STOCK.c.u[k]=2;check('conteo corregido elimina discrepancia',!o().revisarStock&&o().pedir===0);
seed([]);STATE=[pedido('Fabricacion',2,diasAdelante(1),'ok')];STATE[0].productos[0].enProd=true;check('producción para cliente no consume depósito',o().comp===0&&!o().revisarStock);
return checks;});checks.forEach(([n,v])=>console.log((v?'OK ':'FALLO ')+n));assert(checks.every(x=>x[1]));assert.deepEqual(errors,[]);console.log(checks.length+' comprobaciones sin errores JS');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});

